version: '3'

services:
  pg-db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: public
    ports:
      - 15432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  db-volume: